import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const sourceRoot = new URL("../src/", import.meta.url);
const read = (name) => readFile(new URL(name, sourceRoot), "utf8");

test("the shell exposes approved landmarks, provenance, search, language and safe states", async () => {
  const [html, client, locale, favicon] = await Promise.all([read("index.html"), read("client.ts"), read("locales.ts"), read("favicon.svg")]);
  assert.match(html, /<header id="topbar" class="topbar"/u);
  assert.match(html, /class="app-mark" src="favicon\.svg" alt=""/u);
  assert.match(html, /<aside id="sidebar" class="sidebar"/u);
  assert.match(html, /<main id="content" tabindex="-1">/u);
  assert.match(html, /type="search"/u);
  assert.match(html, /id="branch-selector"/u);
  assert.match(html, /id="branch-search" type="search"/u);
  assert.match(html, /data-language="uk"/u);
  assert.match(html, /data-language="en"/u);
  assert.match(html, /data-language="side"/u);
  assert.match(html, /id="language-switch" class="segmented" role="group" aria-label="Plan language"/u);
  assert.doesNotMatch(html, /translation-disclosure/u);
  assert.match(client, /Detached HEAD/u);
  assert.match(client, /copy\.dirty/u);
  assert.match(client, /copy\.stale/u);
  assert.match(client, /copy\.unsupported/u);
  assert.match(client, /copy\.empty/u);
  assert.match(client, /translation-columns/u);
  assert.match(client, /\/translation/u);
  assert.match(locale, /Провайдера перекладу не вибрано/u);
  assert.match(locale, /перевірені блоки плану передаються/u);
  assert.match(client, /copy\.translationProviderHelpRemote/u);
  assert.match(html, /id="translation-settings"/u);
  assert.match(html, /id="translation-provider"/u);
  assert.match(html, /option value="none"/u);
  assert.match(html, /id="ollama-model"/u);
  assert.match(html, /id="ollama-model-settings" hidden/u);
  assert.match(client, /api\/translation\/providers/u);
  assert.match(client, /"agy", "claude", "codex", "gemini", "qwen", "kimi", "ollama"/u);
  assert.match(client, /translationProviderPreferenceKey/u);
  assert.match(client, /localStorage\.setItem\(translationProviderPreferenceKey/u);
  assert.match(client, /ollamaModelPreferenceKey/u);
  assert.match(client, /return isTranslationProviderPreference\(value\) \? value : "none"/u);
  assert.match(client, /translationGeneration/u);
  assert.match(client, /providerGeneration !== translationGeneration/u);
  assert.match(client, /translationIdentity\(changeId\)/u);
  assert.match(client, /option\.disabled = !provider\.available && provider\.id !== translationProvider/u);
  assert.match(client, /elements\.ollamaSettings\.hidden = descriptor\?\.id !== "ollama"/u);
  assert.doesNotMatch(client, /required\("translation-disclosure"\)/u);
  assert.match(client, /if \(translationProvider === "none"\) return/u);
  assert.match(client, /if \(nextLanguage === "en"\)[\s\S]+setLanguage\("en"\)[\s\S]+return/u);
  assert.doesNotMatch(client, /confirmTranslationDownload/u);
  assert.match(client, /copy\.translationUsage/u);
  assert.match(client, /else if \(section\.body\)/u);
  assert.match(client, /if \(section\.body\) card\.append\(fallbackNotice/u);
  assert.doesNotMatch(html, /id="translation-dialog"/u);
  assert.match(html, /<link rel="icon" href="favicon\.svg" type="image\/svg\+xml">/u);
  assert.match(favicon, /<circle cx="28" cy="31" r="15"/u);
  assert.match(favicon, /m38 35 6 6 11-14/u);
  assert.match(client, /snapshot\.branches\.recent/u);
  assert.match(client, /snapshot\.branches\.all\.filter/u);
  assert.match(client, /\/worktrees\/\$\{encodeURIComponent\(branch\.worktreeId\)\}\//u);
  assert.doesNotMatch(client, /copy\.goToArtifact/u);
  assert.doesNotMatch(locale, /Перейти до \$\{label\}/u);
  assert.match(client, /artifact-proposal/u);
  assert.match(client, /setAttribute\("role", "tablist"\)/u);
  assert.match(client, /setAttribute\("role", "tab"\)/u);
  assert.match(client, /setAttribute\("role", "tabpanel"\)/u);
  assert.match(client, /setAttribute\("aria-selected", String\(selected\)\)/u);
  assert.match(client, /artifact\.panel\.hidden = !selected/u);
  assert.match(client, /history\.pushState\(null, "", `#\$\{selectedArtifact\.target\}`\)/u);
  assert.match(client, /addEventListener\("popstate"/u);
  assert.match(client, /event\.key === "ArrowRight"/u);
  assert.match(client, /event\.key === "ArrowLeft"/u);
  assert.match(client, /event\.key === "Home"/u);
  assert.match(client, /event\.key === "End"/u);
  assert.match(locale, /design: "Дизайн"/u);
  assert.match(client, /arrangeChangeTree\(group\.items\)/u);
  assert.match(client, /role", "listitem/u);
  assert.match(client, /dataset\.treeLevel/u);
  assert.match(client, /dataset\.parentChangeId/u);
  assert.match(client, /copy\.dependsOn/u);
  assert.match(client, /copy\.additionalDependencies/u);
  assert.match(client, /isArchiveReadyChange/u);
  assert.match(client, /copy\.readyToArchive/u);
  assert.match(client, /copy\.archiveReadyCue/u);
  assert.match(client, /localStorage\.getItem\(languagePreferenceKey\)/u);
  assert.match(client, /localStorage\.setItem\(languagePreferenceKey/u);
  assert.match(client, /restoreCachedTranslation/u);
  assert.match(client, /completeMissingTranslation\(id\)/u);
  assert.match(client, /translationRequests/u);
  assert.match(client, /translation-pending/u);
  assert.match(client, /copy\.translationPending/u);
  assert.match(html, /id="brand-home"/u);
  assert.match(html, /id="activity-details"/u);
  assert.match(html, /id="activity-live"/u);
  assert.match(client, /stablePublicRoute \? "\/"/u);
  assert.match(client, /api\/activity/u);
  assert.match(client, /addEventListener\("activity"/u);
  assert.match(client, /addEventListener\("ready"/u);
  assert.match(client, /addEventListener\("stale"[\s\S]+queueLiveRefresh\(\)/u);
  assert.match(client, /for \(let attempt = 0; attempt < 4; attempt \+= 1\)/u);
  assert.match(client, /api<Snapshot>\("api\/snapshot"\)/u);
  assert.match(client, /refreshed\.changes\.some\(\(change\) => change\.id === previousSelection\)/u);
  assert.match(client, /detailCache\.clear\(\)/u);
  assert.doesNotMatch(client, /location\.reload/u);
  assert.match(client, /activityKindSet/u);
  assert.match(client, /isSafeActivityPath/u);
  assert.match(client, /copy\.activitySourceChanged\(entry\.data\.paths/u);
  assert.match(client, /textContent = copy\.activityCount/u);
  assert.doesNotMatch(client, /innerHTML/u);
  assert.match(client, /refreshVerification/u);
  assert.match(client, /detailCache/u);
  assert.match(client, /translationNotCached/u);
  assert.match(client, /translationProviderAuthRequired/u);
  assert.match(locale, /ukUA/u);
  assert.match(locale, /Пошук планів/u);
  assert.match(locale, /Залежить від/u);
  assert.match(locale, /Готові до архівації/u);
  assert.match(locale, /Лише спостережувані події/u);
  assert.match(locale, /Повернутися до всіх проєктів/u);
});

test("the optional Hub exposes explicit project cards without plan editing controls", async () => {
  const [html, client, css, locale] = await Promise.all([read("hub.html"), read("hub-client.ts"), read("hub.css"), read("locales.ts")]);
  assert.match(html, /id="projects"/u);
  assert.match(html, /class="hub-brandbar"/u);
  assert.match(html, /class="app-mark" src="\/favicon\.svg" alt=""/u);
  assert.match(client, /copy\.hubDescription/u);
  assert.match(locale, /Лише проєкти, які ви явно зареєстрували/u);
  assert.match(client, /\/api\/projects/u);
  assert.match(html, /id="add-project"/u);
  assert.match(html, /id="registration-dialog"/u);
  assert.match(html, /id="removal-dialog"/u);
  assert.match(html, /<link rel="icon" href="\/favicon\.svg" type="image\/svg\+xml">/u);
  assert.match(client, /\/api\/project-registration-intents/u);
  assert.match(client, /copy\.removeFromHub/u);
  assert.match(client, /If-Match/u);
  assert.match(client, /location\.assign\(target\)/u);
  assert.doesNotMatch(`${html}\n${client}`, /edit|comment|checkout|switch/iu);
  assert.match(css, /@media \(max-width: 560px\)/u);
  assert.match(css, /prefers-reduced-motion/u);
});

test("the client renders repository text as inert text and preserves reload capability per tab", async () => {
  const client = await read("client.ts");
  assert.match(client, /\.textContent = text/u);
  assert.doesNotMatch(client, /innerHTML/u);
  assert.match(client, /sessionStorage\.setItem\("openspec-workbench-capability"/u);
  assert.match(client, /history\.replaceState\(null, "", `\$\{publicBase\}\$\{location\.hash\}`\)/u);
});

test("provider execution uses a bounded authorized-user environment and safe diagnostics", async () => {
  const [agy, runner, providers] = await Promise.all([read("agy-translation.ts"), read("bounded-process.ts"), read("translation-providers.ts")]);
  assert.match(runner, /environment\.HOME = os\.homedir\(\)/u);
  assert.match(runner, /environment\.BROWSER/u);
  assert.match(runner, /shell: false/u);
  assert.match(runner, /process\.kill\(-child\.pid/u);
  assert.match(agy, /gemini-3\.6-flash-high/u);
  assert.doesNotMatch(agy, /"--effort", "low"/u);
  assert.match(runner, /64 \* 1024/u);
  assert.match(providers, /translationProviderIds/u);
  assert.doesNotMatch(`${agy}\n${providers}`, /openrouter|deepseek/iu);
});

test("the responsive fixture collapses navigation, prevents overflow and respects reduced motion", async () => {
  const css = await read("styles.css");
  assert.match(css, /@media \(max-width: 760px\)/u);
  assert.match(css, /\.artifact-tabs \{[^}]*overflow-x: auto/u);
  assert.match(css, /\.artifact-tabs button\[aria-selected="true"\]/u);
  assert.match(css, /\.artifact-panel/u);
  assert.match(css, /\.activity-panel/u);
  assert.match(css, /\.activity-details/u);
  assert.match(css, /\.sidebar\[data-collapsed="true"\]/u);
  assert.match(css, /\.translation-columns \{ grid-template-columns: 1fr; \}/u);
  assert.match(css, /\.change-tree-row\.child/u);
  assert.match(css, /max-width: calc\(100% - \.8rem\)/u);
  assert.match(css, /max-width: calc\(100% - \.4rem\)/u);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)/u);
  assert.match(css, /overflow-wrap: anywhere/u);
});

test("translation settings stay contextual, wide, and above plan content", async () => {
  const css = await read("styles.css");
  assert.match(css, /\.topbar \{[^}]*position: relative;[^}]*z-index: 40;/u);
  assert.match(css, /\.plan-controls \{[^}]*position: relative;[^}]*z-index: 20;/u);
  assert.match(css, /\.translation-settings-panel \{[^}]*width: min\(34rem, calc\(100vw - 2rem\)\);[^}]*z-index: 30;/u);
  assert.match(css, /\.translation-settings-panel select \{[^}]*width: 100%;/u);
  assert.match(css, /#ollama-model-settings\[hidden\] \{ display: none; \}/u);
  assert.match(css, /\.skip-link \{[^}]*z-index: 100;/u);
});
