export { detectGitDirtyForTesting, discoverGitSnapshot, discoverLocalBranches, inspectOpenSpecCandidate, projectBranchNavigation, runGitCommandForTesting, safeReadProjectFile } from "./git.js";
export { ActivityJournal, activityDiagnostic, activityKinds } from "./activity.js";
export { ProjectRegistry, defaultWorkbenchStateDirectory, validateRegisteredProject, validateRegisteredProjectRoot } from "./registry.js";
export { adaptArtifactStatus, adaptChangeList, adaptDoctor, adaptValidation, createPinnedOpenSpecRunner, npmCliCandidatesForTesting } from "./openspec.js";
export { compatibilityManifest, validateCompatibilityManifestForTesting, verifyOpenSpecCompatibility } from "./compatibility.js";
export { buildChangeDetail, buildChangePreview, buildChangeVerification, buildSnapshot, deriveTreeParents, listChanges, parseExplicitChangeDependencies, parseSections, parseTasks } from "./projection.js";
export { arrangeChangeTree } from "./change-tree.js";
export { isArchiveReadyChange, isCompletedChange } from "./change-lifecycle.js";
export { TranslationCache, TranslationService, defaultTranslationStateDirectory, maskProtectedText, restoreProtectedText, screenTranslationBlock, translationCacheKey } from "./translation.js";
export { classifyAgyFailureForTesting, parseAgyTranslationOutput } from "./agy-translation.js";
export { AgyTranslationAdapter } from "./agy-translation.js";
export { probeExecutable, runBoundedProcess } from "./bounded-process.js";
export { buildCliInvocation, CliTranslationAdapter, parseCliTranslationOutput } from "./cli-translation.js";
export { buildTranslationPrompt, classifyProviderFailure, parseJsonPayload, TRANSLATION_OUTPUT_SCHEMA, validateTranslationPayload } from "./translation-contract.js";
export { discoverOllamaModels, OllamaTranslationAdapter, validateOllamaModel } from "./ollama-translation.js";
export { isTranslationProviderId, isTranslationProviderPreference, translationProviderIds, TranslationProviderRegistry } from "./translation-providers.js";
export { openSpecContentIdentity, openSpecContentState, SnapshotWatcher } from "./watcher.js";
export { WorkbenchError } from "./types.js";
export { MacFolderPicker, RegistrationIntents, WindowsFolderPicker, createNativeFolderPicker, decodeMacFolderPickerOutputForTesting, decodeWindowsFolderPickerOutputForTesting } from "./registration.js";
